###Create one trip
POST http://localhost:9003/trips
Content-Type: application/json

{
  "origin": {
    "latitude": 1234.5678,
    "longitude": 1234.5678
  },
  "destination": {
    "latitude": 1.5678,
    "longitude": 1234.5678
  },
  "departureDate": "2022-12-11",
  "driverId": 1,
  "availableSeating": 4
}

###Read one trip
GET http://localhost:9003/trips/1
Content-Type: application/json

###Read the trips of a driver
GET http://localhost:9003/trips/driver/2
Content-Type: application/json

###Delete one trip
DELETE http://localhost:9003/trips/1
Content-Type: application/json

###Delete all trips of a driver
DELETE http://localhost:9003/trips/driver/1
Content-Type: application/json

###Get 20 firsts trips
GET http://localhost:9003/trips
Content-Type: application/json

###Get 20 firsts trips with date filter
GET http://localhost:9003/trips?departureDate=2022-12-11
Content-Type: application/json

###Get 20 firsts trips with origin filter
GET http://localhost:9003/trips?originLat=1234.5678&originLon=12.678
Content-Type: application/json

###Get 20 firsts trips with dest filter
GET http://localhost:9003/trips?destinationLat=1234.5678&destinationLon=12.678
Content-Type: application/json

###Get 20 firsts trips with origin and dest filter
GET http://localhost:9003/trips?destinationLat=1234.5678&destinationLon=12.678&originLat=1234.5678&originLon=12.678
Content-Type: application/json
