### Create passenger
POST http://localhost:8080/passenger
Content-Type: application/json

{
  "id": 1,
  "trip_id": 1,
  "user_id": 1,
  "status": "PENDING"
}

### Read passenger
GET http://localhost:8080/passenger/1
