openapi: 3.0.3
info: 
  title: Project calculatedDistance service
  description: Microserice handling trips database
  version: 1.0.1
servers:
  - url: http://localhost:9001
    description: Development server

paths:

  /calculatedDistance/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          example: 38
        description: ID of the trip
    get:
      summary: Get the calculated distance
      responses:
        404:
          description: No trip found with this ID
        200:
          description: Sent the distance
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/calculatedDistance'

components:
  securitySchemes:
    authentication:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    calculatedDistance:
      type: object
      properties:
        idTrip:
          type: integer
        distance:
          type: number
        
      example:
        idTrip: 12
        distance: 52.10

