openapi: 3.0.3
info: 
  title: Project calculatedDistance service
  description: Microserice handling trips database
  version: 1.0.1
servers:
  - url: http://localhost:9001
    description: Development server

paths:

  /calculatedDistance/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          example: 38
        description: ID of the trip
    get:
      summary: Get the calculated distance
      responses:
        404:
          description: No trip found with this ID
        200:
          description: Sent trip information
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/calculatedDistance'

  /calculatedDistance/:
    get:
      summary: Get the calculated distance
      requestBody:
        description: Information of the trip
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/positionHolder'
      responses:
        400:
          description: Bad request
        200:
          description: Sent trip information
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/calculatedDistance'

components:
  securitySchemes:
    authentication:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    position:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
      example:
        latitude: 50.849372
        longitude: 4.451009

    positionHolder:
      type: object
      properties:
        origin:
          $ref: '#/components/schemas/position'
        destination:
          $ref: '#/components/schemas/position'
      example:
        origin:
          latitude: 50.849372
          longitude: 4.451009
        destination:
          latitude: 50.849372
          longitude: 4.451009


    calculatedDistance:
      type: object
      properties:
        idTrip:
          type: integer
        distance:
          type: number
      example:
        idTrip: 12
        distance: 52.10

    distance:
      type: object
      properties:
        distance:
          type: number
      example:
        distance: 52.10